/*
 * MDIO_config.h
 *
 *  Created on: Sep 4, 2022
 *      Author: emad
 */

#ifndef MCAL_MDIO_CONFIG_H_
#define MCAL_MDIO_CONFIG_H_

/*Configure DIO Pin Direction*/

/*
 * DIO_PIN_INPUT
 * DIO_PIN_OUTPUT
 */
#define MDIO_DDRA_PIN0     MDIO_PIN_INPUT
#define MDIO_DDRA_PIN1     MDIO_PIN_INPUT
#define MDIO_DDRA_PIN2     MDIO_PIN_INPUT
#define MDIO_DDRA_PIN3     MDIO_PIN_INPUT
#define MDIO_DDRA_PIN4     MDIO_PIN_INPUT
#define MDIO_DDRA_PIN5     MDIO_PIN_OUTPUT
#define MDIO_DDRA_PIN6     MDIO_PIN_OUTPUT
#define MDIO_DDRA_PIN7     MDIO_PIN_OUTPUT

#define MDIO_DDRB_PIN0     MDIO_PIN_OUTPUT
#define MDIO_DDRB_PIN1     MDIO_PIN_OUTPUT
#define MDIO_DDRB_PIN2     MDIO_PIN_OUTPUT
#define MDIO_DDRB_PIN3     MDIO_PIN_OUTPUT
#define MDIO_DDRB_PIN4     MDIO_PIN_INPUT
#define MDIO_DDRB_PIN5     MDIO_PIN_INPUT
#define MDIO_DDRB_PIN6     MDIO_PIN_INPUT
#define MDIO_DDRB_PIN7     MDIO_PIN_INPUT

#define MDIO_DDRC_PIN0     MDIO_PIN_OUTPUT
#define MDIO_DDRC_PIN1     MDIO_PIN_OUTPUT
#define MDIO_DDRC_PIN2     MDIO_PIN_OUTPUT
#define MDIO_DDRC_PIN3     MDIO_PIN_OUTPUT
#define MDIO_DDRC_PIN4     MDIO_PIN_OUTPUT
#define MDIO_DDRC_PIN5     MDIO_PIN_OUTPUT
#define MDIO_DDRC_PIN6     MDIO_PIN_OUTPUT
#define MDIO_DDRC_PIN7     MDIO_PIN_OUTPUT

#define MDIO_DDRD_PIN0     MDIO_PIN_INPUT
#define MDIO_DDRD_PIN1     MDIO_PIN_INPUT
#define MDIO_DDRD_PIN2     MDIO_PIN_INPUT
#define MDIO_DDRD_PIN3     MDIO_PIN_OUTPUT
#define MDIO_DDRD_PIN4     MDIO_PIN_OUTPUT
#define MDIO_DDRD_PIN5     MDIO_PIN_OUTPUT
#define MDIO_DDRD_PIN6     MDIO_PIN_OUTPUT
#define MDIO_DDRD_PIN7     MDIO_PIN_OUTPUT

/*Configure DIO Pin Value*/
/*
 * DIO_PIN_LOW
 * DIO_PIN_HIGH
 */

#define MDIO_PORTA_PIN0     MDIO_PIN_LOW
#define MDIO_PORTA_PIN1     MDIO_PIN_LOW
#define MDIO_PORTA_PIN2     MDIO_PIN_LOW
#define MDIO_PORTA_PIN3     MDIO_PIN_LOW
#define MDIO_PORTA_PIN4     MDIO_PIN_LOW
#define MDIO_PORTA_PIN5     MDIO_PIN_LOW
#define MDIO_PORTA_PIN6     MDIO_PIN_LOW
#define MDIO_PORTA_PIN7     MDIO_PIN_LOW

#define MDIO_PORTB_PIN0     MDIO_PIN_HIGH
#define MDIO_PORTB_PIN1     MDIO_PIN_HIGH
#define MDIO_PORTB_PIN2     MDIO_PIN_HIGH
#define MDIO_PORTB_PIN3     MDIO_PIN_HIGH
#define MDIO_PORTB_PIN4     MDIO_PIN_HIGH
#define MDIO_PORTB_PIN5     MDIO_PIN_HIGH
#define MDIO_PORTB_PIN6     MDIO_PIN_HIGH
#define MDIO_PORTB_PIN7     MDIO_PIN_HIGH

#define MDIO_PORTC_PIN0     MDIO_PIN_LOW
#define MDIO_PORTC_PIN1     MDIO_PIN_LOW
#define MDIO_PORTC_PIN2     MDIO_PIN_LOW
#define MDIO_PORTC_PIN3     MDIO_PIN_LOW
#define MDIO_PORTC_PIN4     MDIO_PIN_LOW
#define MDIO_PORTC_PIN5     MDIO_PIN_LOW
#define MDIO_PORTC_PIN6     MDIO_PIN_LOW
#define MDIO_PORTC_PIN7     MDIO_PIN_LOW

#define MDIO_PORTD_PIN0     MDIO_PIN_LOW
#define MDIO_PORTD_PIN1     MDIO_PIN_LOW
#define MDIO_PORTD_PIN2     MDIO_PIN_HIGH
#define MDIO_PORTD_PIN3     MDIO_PIN_LOW
#define MDIO_PORTD_PIN4     MDIO_PIN_LOW
#define MDIO_PORTD_PIN5     MDIO_PIN_LOW
#define MDIO_PORTD_PIN6     MDIO_PIN_LOW
#define MDIO_PORTD_PIN7     MDIO_PIN_LOW


#endif /* MCAL_MDIO_CONFIG_H_ */
